"""add video fields to dream

Revision ID: 4db0853d17ff
Revises: 58390dc7e4ea
Create Date: 2025-06-21 21:48:57.966138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4db0853d17ff'
down_revision: Union[str, None] = '58390dc7e4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dreams', sa.Column('video_s3_key', sa.String(length=512), nullable=True))
    op.add_column('dreams', sa.Column('video_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dreams', 'video_metadata')
    op.drop_column('dreams', 'video_s3_key')
    # ### end Alembic commands ###
