"""add s3_key to AudioSegment

Revision ID: 9779c22c6a1f
Revises: 69eb32edd7df
Create Date: 2025-06-19 19:02:17.530413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9779c22c6a1f'
down_revision: Union[str, None] = '69eb32edd7df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('segments')
    op.drop_table('dreams')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dreams',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('transcript', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('state', postgresql.ENUM('draft', 'completed', name='dreamstate'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dreams_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('segments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dream_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('duration', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transcription', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dream_id'], ['dreams.id'], name='segments_dream_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='segments_pkey')
    )
    # ### end Alembic commands ###
